Repository prixe/lindo, pull requests merged in 2021-12, with the labels that each got.

#150 New Mod: Rune Opener List
  locale/en.json
  locale/es.json
  package-lock.json
  src/app/mods/index.ts
  src/app/mods/rune-lister/runeOpenerLister.ts
  src/app/windows/main/layout/game/game.component.ts
Labels: enhancement, good first issue

#126 New translante pt-br
  electron/i18n/pt.js
  electron/settings/settings.ts
  locale/pt.json
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/windows/main/menus/option/general/general.component.ts
Labels: enhancement, translation

#145 [MOD] Déplacement et Sauvegarde des grips
  src/app/mods/grip-position-save/grip-position-save.ts
  src/app/mods/index.ts
Labels: enhancement

#153 Early Server reload
  src/app/windows/update/update.component.ts
Labels: bug
